# Generated by Django 3.0.2 on 2020-02-25 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('imei', models.CharField(max_length=100)),
                ('plan', models.CharField(max_length=100)),
                ('invoice', models.CharField(max_length=200)),
                ('pics', models.CharField(max_length=200)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('vend', models.CharField(default=None, max_length=10, null=True)),
                ('status', models.CharField(choices=[('Under Review', 'Under Review'), ('Under Claim', 'Under Claim'), ('Rejected', 'Rejected'), ('Approved', 'Approved')], default='Under Review', max_length=30)),
                ('mob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Screen Damage', 'Screen Damage'), ('Liquid Damage', 'Liquid Damage'), ('Unresponsive Touchpad', 'Unresponsive Touchpad'), ('Broken Charging Port', 'Broken Charging Port'), ('Faulty Earphone Jack', 'Faulty Earphone Jack'), ('Other', 'Other')], default='Other', max_length=30)),
                ('issue', models.TextField()),
                ('status', models.CharField(choices=[('Under Review', 'Under Review'), ('Rejected', 'Rejected'), ('Being Processed', 'Being Processed'), ('Approved', 'Approved')], default='Under Review', max_length=30)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claimzy_in.Devices')),
                ('mob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
