# Generated by Django 3.0.2 on 2020-02-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claimzy_in', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devices',
            name='pics',
        ),
        migrations.AddField(
            model_name='devices',
            name='back',
            field=models.FileField(default='/static/claimzy_in/img/default.jpg', max_length=254, upload_to='claimzy_in/userdata/back/'),
        ),
        migrations.AddField(
            model_name='devices',
            name='front',
            field=models.FileField(default='/static/claimzy_in/img/default.jpg', max_length=254, upload_to='claimzy_in/userdata/front/'),
        ),
        migrations.AddField(
            model_name='devices',
            name='imei_pic',
            field=models.FileField(default='/static/claimzy_in/img/default.jpg', max_length=254, upload_to='claimzy_in/userdata/imei/'),
        ),
        migrations.AddField(
            model_name='devices',
            name='price',
            field=models.CharField(default=2000, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devices',
            name='invoice',
            field=models.FileField(default='/static/claimzy_in/img/default.jpg', max_length=254, upload_to='claimzy_in/userdata/invoice/'),
        ),
    ]
