# Generated by Django 3.0.2 on 2020-02-25 21:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('claimzy_in', '0002_auto_20200226_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='invoice_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
