# Generated by Django 3.0.2 on 2020-02-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claimzy_in', '0005_remove_devices_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='invoice_date',
            field=models.DateField(default=None),
        ),
    ]
