# Generated by Django 3.0.2 on 2020-02-25 21:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claimzy_in', '0007_auto_20200226_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='invoice_date',
            field=models.DateField(default=datetime.date(2020, 2, 26)),
            preserve_default=False,
        ),
    ]
