# Generated by Django 3.0.2 on 2020-02-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claimzy_in', '0008_auto_20200226_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='back',
            field=models.FileField(default='static/claimzy_in/img/default.jpg', max_length=254, upload_to='static/claimzy_in/userdata/back/'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='front',
            field=models.FileField(default='static/claimzy_in/img/default.jpg', max_length=254, upload_to='static/claimzy_in/userdata/front/'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='imei_pic',
            field=models.FileField(default='static/claimzy_in/img/default.jpg', max_length=254, upload_to='static/claimzy_in/userdata/imei/'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='invoice',
            field=models.FileField(default='static/claimzy_in/img/default.jpg', max_length=254, upload_to='static/claimzy_in/userdata/invoice/'),
        ),
    ]
