# Generated by Django 3.0.2 on 2021-02-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claimzy_in', '0014_devices_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
