# Generated by Django 3.0.2 on 2021-02-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claimzy_in', '0015_auto_20210222_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='devices',
            name='vend',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
