# Generated by Django 3.0.2 on 2021-02-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claimzy_in', '0016_auto_20210222_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='last_update',
            field=models.DateTimeField(),
        ),
    ]
