# Generated by Django 3.0.2 on 2021-03-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claimzy_in', '0018_auto_20210227_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='imei',
            field=models.CharField(max_length=15),
        ),
    ]
