# Generated by Django 3.0.2 on 2021-02-21 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210221_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='address2',
            new_name='addresstwo',
        ),
    ]
